{
 "title": "Roomba",
 "time": { "from": "now-3d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Charging",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "roomba_charging", "legendFormat": " " }
   ]
  },
  {
   "title": "Cleaning / Charging",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "roomba_has_mission", "legendFormat": "Cleaning" },
    { "expr": "roomba_charging", "legendFormat": "Charging" }
   ]
  },
  {
   "title": "Cleaning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "roomba_has_mission", "legendFormat": " " }
   ]
  },
  {
   "title": "Battery %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "roomba_battery", "legendFormat": "Battery %" }
   ]
  },
  {
   "title": "Battery %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "roomba_battery", "legendFormat": "Battery %" }
   ]
  },
  {
   "title": "Last Cleaning Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "roomba_last_mission_duration > 0",
     "legendFormat": "last duration"
    }
   ]
  }
 ]
}